# project level configuration
docker: java-docker
language: node.js
version: 1.6
cache: true
build_path: ./project_folder_name
env:
 - FLOW_ENV_1=xxx111,FLOW_ENV_2=xxx111
 - FLOW_ENV_3=xxx222
 - FLOW_ENV_4=xxx333

# flow level configuration
flows:
  - name: 123
    docker: open-jdk-1.9-docker
    language: objective-c
    cache: false
    env:
      - FLOW_ENV_5=xxx555
      - FLOW_ENV_6=xxx666

    trigger:
      push:
        - develop
        - master
      tag:
        - '*'
      pull_request: true
      schedule:
        - 5, 5, 10, 10

    finalize:
      email:
        success:
          - test1@fir.im
          - test2@fir.im
          - test3@fir.im
        failure:
          - test1@fir.im
          - test2@fir.im
      slack:
        success:
          - xxx
          - xxx
        failure:
          - xxx
      webhook:
        success:
          - xxx
        failure:
          - xxx

    # steps definition, cannot define both plugin and scripts
    steps:
      - name: step_1
        enable: true
        failure: false
        plugin:
          name: xxxx
          inputs:
            - FLOW_WORK_SPACE=12
            - FLOW_WORK_XXXXX=14

      - name: step_2
        scripts:
          - mvn build test

      - name: step_3 # only plugin
        plugin:
          name: redis
          version: 2.3.6

      - name: step_4 # only script
        scripts:
          - mvn finish
          - mvn clean

  - name: flow-2
    trigger:
      push:
        - develop

    # steps definition, cannot define both plugin and scripts
    steps:
      - name: step_1
        enable: true
        failure: false
        plugin:
          name: xxxx
          inputs:
            - FLOW_WORK_SPACE=12
            - FLOW_WORK_XXXXX=14